version: "3.7"
services:

  envoy:
    build:
      context: .
      dockerfile: Dockerfile-envoy
    volumes:
      - ./envoy.yaml:/etc/envoy.yaml
    networks:
      - envoymesh
    expose:
      - "8001"
      - "8010"
    ports:
      - "8000:8000"
      - "8010:8010"

  redis:
    build:
      context: .
      dockerfile: Dockerfile-redis
    networks:
      envoymesh:
        aliases:
          - redis_server
    expose:
      - "6379"
    ports:
      - "6379:6379"

  extauth:
    build: extauth
    networks:
      - envoymesh
    expose:
      - "4000"
    ports:
      - "4000:4000"

  backend:
    build:
      context: backend
    networks:
      - envoymesh
    expose:
      - "8123"
    ports:
      - "8123:8123"


networks:
  envoymesh: {}
